import { Injectable, NestMiddleware } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Request, Response, NextFunction } from 'express';

@Injectable()
export class MaintenanceModeMiddleware implements NestMiddleware {
  constructor(private readonly configService?: ConfigService) {}

  /**
   * Whitelists active operational routes during system maintenance.
   * Verified existing endpoints: /api/health and /api/docs Swagger documentation.
   */
  private isWhitelisted(url: string): boolean {
    if (!url) return false;
    const cleanUrl = url.split('?')[0].toLowerCase();

    return (
      cleanUrl === '/api/health' ||
      cleanUrl.startsWith('/api/health/') ||
      cleanUrl === '/api/docs' ||
      cleanUrl.startsWith('/api/docs/') ||
      cleanUrl.startsWith('/api/docs-json')
    );
  }

  use(req: Request & { id?: string }, res: Response, next: NextFunction) {
    const isMaintenance =
      this.configService?.get<string>('MAINTENANCE_MODE') === 'true' ||
      process.env.MAINTENANCE_MODE === 'true';

    if (!isMaintenance) {
      return next();
    }

    const rawUrl = req.originalUrl || req.url;
    if (this.isWhitelisted(rawUrl)) {
      return next();
    }

    // Set HTTP Retry-After header (300 seconds / 5 minutes)
    res.setHeader('Retry-After', '300');

    // Retrieve request ID generated by RequestLoggingMiddleware
    const requestId = req.id || (req.headers['x-request-id'] as string) || 'req_unknown';

    // Short-circuit request with deliberate HTTP 503 Service Unavailable response
    return res.status(503).json({
      statusCode: 503,
      error: 'Service Unavailable',
      message: 'System is currently undergoing scheduled maintenance.',
      requestId,
    });
  }
}
